qubershipApihubAgentsBackend:
  version: ''
  image:
    repository: 'ghcr.io/netcracker/qubership-apihub-agents-backend'
    tag: 'dev'
  replicas: 1

  resource:
    memory:
      request: "256Mi"
      limit: "256Mi"
    cpu:
      request: "30m"
      limit: "1"

  env:
    logLevel: "INFO"
    database:
      host: 'pg-common.postgres-db.svc.cluster.local'
      port: '5432'
      name: 'apihub_agents_backend'
      username: '' # set username of the user for apihub_agents_backend database
      password: '' # set password for the specified user

    apihubUrl: 'http://qubership-apihub-ui.qubership-apihub.svc.cluster.local:8080'
    accessToken: '' # set access token from qubership-apihub

  ingress:
    enabled: true
    url: 'qubership-apihub-agents-backend.localtest.me'
