openapi: 3.0.3
info:
  title: Qubership APIHUB Agents Backend Admin API
  description: Admin REST API for managing debug and administrative operations in Qubership APIHUB agents backend
  license:
    name: qubership
    url: https://qubership.org
  version: "2024.2"
  x-nc-api-audience: BWC

servers:
  - url: https://{apihubAgentsBackend}.qubership.org
    description: APIHUB server
    variables:
      apihubAgentsBackend:
        description: Name of the APIHUB Agents Backend server.
        enum:
          - apihub-agents-backend
          - dev.apihub-agents-backend
          - staging.apihub-agents-backend
        default: apihub-agents-backend
security:
  - BearerAuth: []
  - CookieAuth: []
  - ApiKeyAuth: []
  - PersonalAccessToken: []
tags:
  - name: Debug
    description: Debug and logging operations
paths:
  /api/v1/debug/logs/checkLevel:
    get:
      tags:
        - Debug
      summary: Check log level
      description: |
        Check current log level.
      operationId: checkLogLevel
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: string
                description: Current log level
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'
  /api/v1/debug/logs/setLevel:
    post:
      tags:
        - Debug
      summary: Set log level
      description: |
        Set log level.
      operationId: setLogLevel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - level
              properties:
                level:
                  type: string
                  description: Log level to set
                  enum:
                    - panic
                    - fatal
                    - error
                    - warn
                    - info
                    - debug
                    - trace
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  level:
                    type: string
                    description: Current log level
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CustomError:
      type: object
      description: An error description
      properties:
        status:
          type: integer
          description: HTTP status code
        code:
          type: string
          description: Internal string error code. Mandatory in response.
        message:
          type: string
          description: Error message
        debug:
          type: string
          description: Debug information
        params:
          type: object
          additionalProperties: true
          description: Error parameters
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CustomError'
    Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CustomError'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CustomError'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token authentication.
    CookieAuth:
      type: apiKey
      in: cookie
      name: apihub-access-token
      description: Authentication via the `apihub-access-token` cookie.
    ApiKeyAuth:
      type: apiKey
      in: header
      name: api-key
      description: API key authentication.
    PersonalAccessToken:
      type: apiKey
      in: header
      name: X-Personal-Access-Token
      description: Personal Access Token authentication
